global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nexus-nodes'
    static_configs:
      - targets:
        - '139.100.207.199:9100'
        - '139.100.207.83:9100'
        - '139.100.207.102:9100'
        - 'host.docker.internal:9103'
        - 'host.docker.internal:9104'
        - 'host.docker.internal:9105'   
#       - '10.177.40.76:9100'
#       - '10.177.40.113:9101'